import Allworkshops from "./Allworkshops";

export const metadata = {
  title: "AI Expert Career | Workshops",
  description: "Generated by create next app",
};


export default function Page(){
  return(
    <Allworkshops/>
  )
}