import getexperts from "@/lib/getexperts";

export const metadata = {
  title: "AI Expert Career | Our Experts",
  description: "Generated by create next app",
};


export default async function page() {
    const experts = await getexperts();
    const language = "en"
    return(
        <div className="w-11/12 mx-auto mb-10 md:w-9/12 mt-28">
        <div className="w-full p-4 mx-auto mb-12 text-center rounded-md bg-slate-50">
            <h1 className="mb-8 text-3xl font-semibold text-center md:text-4xl">
              {language == "bn"
                ? "প্রোজেক্ট বেজড "
                :"Meet Our Honorable " }{language == "bn"? <span className="mb-4 text-red-500 curved-underline">ওয়ার্কসপ</span> : <span className="text-red-500 curved-underline">Experts</span>}
            </h1>
          <p className="px-2 text-xl text-black md:px-28">we are proud to recognize and celebrate the brilliance and dedication of our foremost experts in the AI industry.Their insightful contributions in the AI industry and AI Education are the cornerstones of the AI revolution.We are deeply grateful for their contributions and remain committed to supporting their vision of a smarter, more equitable world driven by artificial intelligence.</p>
        </div>
        
        
        <div className="grid justify-center gap-5 m-3 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {experts?.map((d, i)=>  
            <div key={i} className="grid grid-cols-1 mx-auto mt-8 mb-10 avatar">
                <div className=" w-full transition-opacity rounded-[7px] shadow-lg shadow-purple-300 ">
                <img src={d.photo} />
                <div className=" absolute inset-0 font-bold transition-opacity duration-700 delay-200 bg-black bg-opacity-30 rounded-[7px] opacity-0 hover:opacity-100 ">
                    <div className="p-2 relative top-[75%] h-[25%] bg-red-600/70 rounded-md">
                    <span className="text-white text-md ">{d.name}</span> <br />
                    <span className="text-[90%] text-white ">{d.designation},{d.company}</span> <br />     
                    </div>
                </div>
                </div>
            </div>
            )}    
        </div>
      </div>
    );
};
