import { Inter } from "next/font/google";
import Navigate from "@/app/components/Navigate";
import "./globals.css";
import Footer from "@/app/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Expert Career",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <link rel="icon" href="/fav.ico" sizes="any" />
        <Navigate />
        {children}
        <Footer />
      </body>
    </html>
  );
}
