import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/app/components/footer/Footer";
import Navbar from "./components/navbar/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AI Expert Career | Home",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <link rel="icon" href="/fav.ico" sizes="any" />
        <Navbar/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
