import Allblogs from "./Allblogs";

export const metadata = {
    title: "AI Expert Career | Blogs",
    description: "Generated by create next app",
};


export default function page(params) {
    return(
        <Allblogs/>
        
    )
};
