import SidePanel from "./Sidepanel";

export const metadata = {
  title: "AI Expert Career | Policies",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <div className="relative min-h-screen mt-20 ">
        <div className="lg:grid grid-cols-[400px_4fr] max-w-full">
            <SidePanel/>
            <div>
            {children}
            </div>
        </div>
    </div>
  );
}